### ISSUE TITLE
Link to non existing template

### ISSUE THREAD

**Issue by TobiasVondracek** [Kentico/gatsby-starter-kontent-lumen#28]
### Brief bug description

In the https://github.com/kentico/gatsby-starter-kontent-lumen#getting-started, the last line of point 3 links to not existing template

### Repro steps

1. Go to https://github.com/kentico/gatsby-starter-kontent-lumen#getting-started, point 3
2. Click on [Template Manager UI](https://kentico.github.io/kontent-template-manager/import-from-file)
3. See blank page (error in console)

### Expected behavior

no link to non existing/error pages

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

Add links to screenshots, if possible.

**Comment by Simply007** [comment]
I have removed the link to the UI since the backup package is version-specific and the version of the backup tool might differ in the UI and the backup package.

Adjust the commit: https://github.com/Kentico/gatsby-starter-kontent-lumen/commit/61e02471eb75acb5e0e7cd4923eb1868b921eff7
